apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-yaml
    method: fromMohit
    another: NewLableForthePod 
    anotherone: MohitsLabel
  name: nginx-yaml
spec:
  containers:
  - image: nginx
    name: nginx-first  
  - image: nginx
    name: nginx-second
